// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGywEcTaiZtPhwm4UwwZbXGSAs7bA7q8Y',
    appId: '1:410948197514:web:54d0713e0d67b66579a173',
    messagingSenderId: '410948197514',
    projectId: 'crud-sistem-4321d',
    authDomain: 'crud-sistem-4321d.firebaseapp.com',
    storageBucket: 'crud-sistem-4321d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj0_o-4oC-k0p_x6muB5tPzT1gEEcLAg4',
    appId: '1:410948197514:android:914f43f12762756879a173',
    messagingSenderId: '410948197514',
    projectId: 'crud-sistem-4321d',
    storageBucket: 'crud-sistem-4321d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ0laHs3UHTxcjxpY3d8PyPyrTbYUsAu8',
    appId: '1:410948197514:ios:7d8554388456660a79a173',
    messagingSenderId: '410948197514',
    projectId: 'crud-sistem-4321d',
    storageBucket: 'crud-sistem-4321d.appspot.com',
    iosBundleId: 'com.example.aplikasiKopi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ0laHs3UHTxcjxpY3d8PyPyrTbYUsAu8',
    appId: '1:410948197514:ios:7d8554388456660a79a173',
    messagingSenderId: '410948197514',
    projectId: 'crud-sistem-4321d',
    storageBucket: 'crud-sistem-4321d.appspot.com',
    iosBundleId: 'com.example.aplikasiKopi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGywEcTaiZtPhwm4UwwZbXGSAs7bA7q8Y',
    appId: '1:410948197514:web:c5c0a9da1eb6039b79a173',
    messagingSenderId: '410948197514',
    projectId: 'crud-sistem-4321d',
    authDomain: 'crud-sistem-4321d.firebaseapp.com',
    storageBucket: 'crud-sistem-4321d.appspot.com',
  );
}
